version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "10080:80"
    links:
      - mysql
    volumes:
      - ./www:/var/www/html

